name : install dependency
on: 
  push:
    paths: 
      - '.github/workflows/npminstall.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
         persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org'
  
    - name : "install npm"
      run: |
          npm install 
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PackagePAT2 }}
        ANOTHER_TOKEN: ${{ secrets.PackagePAT2 }}
    # git+https://$ANOTHER_TOKEN:x-oauth-basic@github.com/yanjingzhu/npmpackages.git
    - name : install private github repo
      run: |
         npm install 
      env: 
         ANOTHER_TOKEN: ${{ secrets.PackagePAT2 }}

