name : install dependency
on: 
  push:
    paths: 
      - '.github/workflows/npminstall.yml'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with: 
         persist-credentials: false

  
    # git+https://$ANOTHER_TOKEN:x-oauth-basic@github.com/yanjingzhu/npmpackages.git 123
    - name : install private github repo
      run: |
         npm install git+https://$ANOTHER_TOKEN:x-oauth-basic@github.com/yanjingzhu/npmpackages.git
      env: 
         ANOTHER_TOKEN: ${{ secrets.npminstallPAT }}
         NODE_AUTH_TOKEN: ${{ secrets.PackagePAT2 }}
