name: post message to slack
on: push
jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps: 
    - name: Notify slack
      env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
         args: '{\"channel\":\"D42GWUG7N\",\"text\":\"Hello world\"}'
