name: test my FirstJSAction
on:   push

jobs:
  create_tag:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - uses: Yanjingzhu/FirstJSAction@master
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'v1.1'
          message: 'Release test'
          commit: ${{ github.sha }}
